[package]
name = "bcryptrs_native"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
name = "bcryptrs_native"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
bcrypt = "0.15.1"
rustler = "0.34.0"
